# Generated by Django 4.2 on 2023-06-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bp_django",
            "0002_answer_dialogue_page_question_userdialogue_userword_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userword",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_words",
                to="bp_django.user",
            ),
        ),
        migrations.AlterField(
            model_name="userword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_words",
                to="bp_django.word",
            ),
        ),
    ]
