# Generated by Django 4.2 on 2023-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bp_django", "0004_rename_pronounce_score_userword_pronunce_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question_inner_id",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="user_inner_id",
        ),
        migrations.RemoveField(
            model_name="dialogue",
            name="book_inner_id",
        ),
        migrations.RemoveField(
            model_name="page",
            name="book_inner_id",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user_inner_id",
        ),
        migrations.RemoveField(
            model_name="userdialogue",
            name="dialogue_inner_id",
        ),
        migrations.RemoveField(
            model_name="userdialogue",
            name="user_inner_id",
        ),
        migrations.RemoveField(
            model_name="userword",
            name="user_inner_id",
        ),
        migrations.RemoveField(
            model_name="userword",
            name="word_inner_id",
        ),
        migrations.RemoveField(
            model_name="voice",
            name="user_inner_id",
        ),
        migrations.RemoveField(
            model_name="voicebook",
            name="book_inner_id",
        ),
        migrations.RemoveField(
            model_name="voicebook",
            name="voice_inner_id",
        ),
        migrations.RemoveField(
            model_name="word",
            name="book_inner_id",
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userword",
            name="pronunce_score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
    ]
