# Generated by Django 4.2 on 2023-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bp_django", "0006_voice_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogue",
            name="meaning",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="dialogue",
            name="text",
            field=models.CharField(max_length=200),
        ),
    ]
