# Generated by Django 4.2 on 2023-06-27 08:30

import bp_django.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bp_django", "0008_remove_voicebook_voice_delete_voice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                ("inner_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("vocal_name", models.CharField(max_length=50)),
                ("path_to_voice_file", models.CharField(max_length=200)),
                (
                    "sythesis_status",
                    models.CharField(
                        max_length=50, validators=[bp_django.models.validate_syn_status]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voices",
                        to="bp_django.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="voicebook",
            name="voice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voicebooks",
                to="bp_django.voice",
            ),
            preserve_default=False,
        ),
    ]
