# Generated by Django 4.2 on 2023-06-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bp_django",
            "0010_rename_pronounce_score_userdialogue_pronunce_score_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="title",
        ),
    ]
